# Generated by Django 4.0.4 on 2022-05-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default='Unknown author', max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='creation_date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
